FROM python:3.11-slim

ENV SET_CONTAINER_TIMEZONE=true
ENV CONTAINER_TIMEZONE=UTC

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app/server
ENV WORKDIR=/app/server
# Install system dependencies and Python
RUN apt-get clean && \
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    vim \
    cron \
    less \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

# Create log directories
RUN mkdir /app/logs

# Copy setup files
COPY server/setup/requirements.txt /opt/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/requirements.txt

COPY server/setup/init.sh /opt/init.sh

# Moving common directories
COPY server /app/server

ENTRYPOINT ["bash","/opt/init.sh"]