# Base image with Python 3.11
FROM python:3.11-slim

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app
# Install system dependencies and Python
RUN apt-get clean && \
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    vim \
    cron \
    less \
    && rm -rf /var/lib/apt/lists/*

# # Install Python dependencies
COPY ./api/requirements.txt /app/api/requirements.txt
RUN pip3 install --no-cache-dir -r /app/api/requirements.txt

COPY ./api /app/api

# Start both server in development mode
CMD ["sh", "-c", "cd /app/api &&  python3 run.py"]